
version: 2

# Add test cases to ensure ORDER_PURCHASE_YEAR and ORDER_STATUS are not null.
models:
  - name: fct_orders
    description: "olist orders model."

    columns:
      - name: order_purchase_year
        description: "Purchase year of the order."
        data_tests:
          - not_null

      - name: order_status
        description: "Status of the order."
        data_tests:
          - not_null

      - name: cnt_distinct_order
        description: "Total number of distinct orders."

      - name: cnt_distinct_customer
        description: "Total number of distinct customers."

  - name: fct_orders_geography
    description: "olist model adding geographical info to orders."
    
    columns:
      - name: order_purchase_year
        description: "Purchase year of the order."
        data_tests:
          - not_null

      - name: order_status
        description: "Status of the order."
        data_tests:
          - not_null

      - name: customer_city
        description: "Customer city."
        data_tests:
          - not_null

      - name: customer_state
        description: "Customer state."
        data_tests:
          - not_null

      - name: cnt_distinct_order
        description: "Total number of distinct orders."

      - name: cnt_distinct_customer
        description: "Total number of distinct customers."

  - name: fct_seller_performance
    description: "olist model for seller performance."
    
    columns:
      - name: seller_id
        description: "Seller primary key"
        data_tests:
          - not_null
          - unique
    
      - name: total_sales_dollar
        description: "Total sales value per seller in $."
    
      - name: cnt_orders
        description: "Total number of individual order items per seller."
    
      - name: cnt_orders_dist
        description: "Total number of orders per seller."
