services: 
  my-python-service: 
    image: python:3.11-slim  # choose sth different from Dockerfile to test build
    container_name: python_app_w3d5act2
    build: 
      context: .
      dockerfile: Dockerfile 
    #command: ["sh", "-c", "python -u app.py && tail -f /dev/null"]  # will keep container UP
    command:  ["python", "-u", "app/app.py"]  # container will EXIT after execution

  # note: if connected to db-service with pgadmin, disconnect before restarting an updated database service
  #       to avoid misleading error messages from server in container (e.g. changing DB_NAME)
  my-database-service: 
    image: postgres:16
    container_name: postgres_db_w3d5act2
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports: 
      - "5433:5432"  # expose port for external access (optional)
